version: '3.8'

services:
  # Laravel API Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    networks:
      - recipe-network

volumes:
  mysql_data:

networks:
  recipe-network:
